[package]
name = "scst"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
regex = "1.11.0"
serde = "1.0.210"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false